// flow-typed signature: e7724ab4055501c7ee928247b88b1db0
// flow-typed version: <<STUB>>/babel-plugin-inline-package-json_v^2.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-inline-package-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-inline-package-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-inline-package-json/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-inline-package-json/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-inline-package-json/lib/index'>;
}
