// flow-typed signature: 667a038be161f37893fa1c2ebb2aa00e
// flow-typed version: <<STUB>>/fallback-cli_v^2.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fallback-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fallback-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fallback-cli/default-runner' {
  declare module.exports: any;
}

declare module 'fallback-cli/normalize-args' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fallback-cli/default-runner.js' {
  declare module.exports: $Exports<'fallback-cli/default-runner'>;
}
declare module 'fallback-cli/index' {
  declare module.exports: $Exports<'fallback-cli'>;
}
declare module 'fallback-cli/index.js' {
  declare module.exports: $Exports<'fallback-cli'>;
}
declare module 'fallback-cli/normalize-args.js' {
  declare module.exports: $Exports<'fallback-cli/normalize-args'>;
}
