// flow-typed signature: 96a2cf3f84f49a071c27ff5d293a4111
// flow-typed version: <<STUB>>/find-up_v^2.1.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-up'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-up' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'find-up/index' {
  declare module.exports: $Exports<'find-up'>;
}
declare module 'find-up/index.js' {
  declare module.exports: $Exports<'find-up'>;
}
