// flow-typed signature: 68de97572393b718ea4969cdb5f160b8
// flow-typed version: <<STUB>>/npmlog_v^4.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npmlog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'npmlog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npmlog/log' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npmlog/log.js' {
  declare module.exports: $Exports<'npmlog/log'>;
}
