// flow-typed signature: c1920f54d36ad10d1e76a86d5b9d420a
// flow-typed version: <<STUB>>/ora_v^1.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ora'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ora' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ora/index' {
  declare module.exports: $Exports<'ora'>;
}
declare module 'ora/index.js' {
  declare module.exports: $Exports<'ora'>;
}
