// flow-typed signature: aa560f856a41f52117cae38341d23938
// flow-typed version: <<STUB>>/p-s_v^3.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-s'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-s' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'p-s/dist/bin-utils/autocomplete/index' {
  declare module.exports: any;
}

declare module 'p-s/dist/bin-utils/index' {
  declare module.exports: any;
}

declare module 'p-s/dist/bin-utils/initialize/index' {
  declare module.exports: any;
}

declare module 'p-s/dist/bin/nps' {
  declare module.exports: any;
}

declare module 'p-s/dist/get-logger' {
  declare module.exports: any;
}

declare module 'p-s/dist/get-script-to-run' {
  declare module.exports: any;
}

declare module 'p-s/dist/get-scripts-from-config' {
  declare module.exports: any;
}

declare module 'p-s/dist/index' {
  declare module.exports: any;
}

declare module 'p-s/dist/kebab-and-camel-casify' {
  declare module.exports: any;
}

declare module 'p-s/dist/resolve-script-object-to-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'p-s/dist/bin-utils/autocomplete/index.js' {
  declare module.exports: $Exports<'p-s/dist/bin-utils/autocomplete/index'>;
}
declare module 'p-s/dist/bin-utils/index.js' {
  declare module.exports: $Exports<'p-s/dist/bin-utils/index'>;
}
declare module 'p-s/dist/bin-utils/initialize/index.js' {
  declare module.exports: $Exports<'p-s/dist/bin-utils/initialize/index'>;
}
declare module 'p-s/dist/bin/nps.js' {
  declare module.exports: $Exports<'p-s/dist/bin/nps'>;
}
declare module 'p-s/dist/get-logger.js' {
  declare module.exports: $Exports<'p-s/dist/get-logger'>;
}
declare module 'p-s/dist/get-script-to-run.js' {
  declare module.exports: $Exports<'p-s/dist/get-script-to-run'>;
}
declare module 'p-s/dist/get-scripts-from-config.js' {
  declare module.exports: $Exports<'p-s/dist/get-scripts-from-config'>;
}
declare module 'p-s/dist/index.js' {
  declare module.exports: $Exports<'p-s/dist/index'>;
}
declare module 'p-s/dist/kebab-and-camel-casify.js' {
  declare module.exports: $Exports<'p-s/dist/kebab-and-camel-casify'>;
}
declare module 'p-s/dist/resolve-script-object-to-string.js' {
  declare module.exports: $Exports<'p-s/dist/resolve-script-object-to-string'>;
}
